apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
    - name: notiflex-alerts
      rules:
        - alert: PodRestartTooMany
          expr: |
            rate(kube_pod_container_status_restarts_total{namespace="notiflex-smb"}[5m]) * 60 * 5 > 3
          for: 1m
          labels:
            severity: critical
            team: smb
          annotations:
            summary: "Pod {{ $labels.pod }} in {{ $labels.namespace }} restarting too often."
            description: "Pod {{ $labels.pod }} has restarted more than 3 times in the last 5 minutes."
