apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: notiflex-pod-restart
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  groups:
    - name: notiflex.rules
      rules:
        - alert: NotiflexPodRestart
          expr: increase(kube_pod_container_status_restarts_total{namespace="notiflex"}[5m]) > 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Notiflex Pod {{ $labels.pod }} restarted"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted."
