apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: notiflex-api
  namespace: enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notiflex-api
  template:
    metadata:
      labels:
        app: notiflex-api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: api-pool
      containers:
        - name: api
          image: asia-northeast3-docker.pkg.dev/project-75fce205-dfa5-4975-a56/notiflex/api:v0.1.1
          env:
            - name: VALKEY_ADDR
              value: valkey-primary.notiflex.svc.cluster.local:6379
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: valkey-password
          ports:
            - containerPort: 8080
  strategy:
    canary:
      steps:
        - setWeight: 100
