apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notiflex-secrets
  namespace: enterprise
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/inlaid-vehicle-484800-n8/secrets/valkey-password/versions/latest"
        path: "valkey-password"
