apiVersion: v1
kind: Service
metadata:
  name: notiflex-api-preview
  namespace: enterprise
spec:
  type: ClusterIP
  selector:
    app: notiflex-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
