apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notiflex-valkey
  namespace: enterprise
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-store
  target:
    name: notiflex-valkey
    creationPolicy: Owner
  data:
    - secretKey: valkey-password
      remoteRef:
        key: valkey-password
        version: latest
