apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notiflex-kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/sysnet4admin/notiflex-platform.git
    targetRevision: main
    path: k8s/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
