apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcpsm-store
spec:
  provider:
    gcpsm:
      projectID: project-75fce205-dfa5-4975-a56
      auth:
        workloadIdentity:
          clusterProjectID: project-75fce205-dfa5-4975-a56
          clusterLocation: asia-northeast3-a
          clusterName: notiflex-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
