apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: notiflex-api-hc
  namespace: notiflex
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: notiflex-api
