apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcpsm-store
spec:
  provider:
    gcpsm:
      projectID: inlaid-vehicle-484800-n8
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-creds
            key: key.json
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notiflex-api-key
  namespace: notiflex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-store
    kind: ClusterSecretStore
  target:
    name: notiflex-api-key
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: notiflex-api-key
